//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uzuri_Swimwear.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public string ACCOUNT_ID { get; set; }
        public string PROVINCE { get; set; }
        public string CITY { get; set; }
        public string SUBURB { get; set; }
        public string STREET_NAME { get; set; }
        public string POSTAL_CODE { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
