//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uzuri_Swimwear.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART_REQUESTS
    {
        public int CART_REQ_ID { get; set; }
        public int CART_ID { get; set; }
        public int CUST_REQ_ID { get; set; }
    
        public virtual CART CART { get; set; }
        public virtual CUSTOMER_REQUEST CUSTOMER_REQUEST { get; set; }
    }
}
