//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uzuri_Swimwear.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSWORD
    {
        public int ACCOUNT_ID { get; set; }
        public byte[] PASSWORD_HASH { get; set; }
        public System.Guid SALT { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
