//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uzuri_Swimwear.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_IMAGES
    {
        public int PRODUCT_ID { get; set; }
        public int IMAGE_ID { get; set; }
        public bool IMAGE_PRIMARY { get; set; }
    
        public virtual IMAGE IMAGE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
